
all:
	python mkPattern.py 40 > pattern-40.svg
	python mkPattern.py 50 > pattern-50.svg
	python mkPattern.py 60 > pattern-60.svg
	python mkPattern.py 65 > pattern-65.svg
	python mkPattern.py 70 > pattern-70.svg
	python mkPattern.py 72 > pattern-72.svg
	python mkPattern.py 75 > pattern-75.svg
	python mkPatternId.py 40 0 > pattern-id-40-0.svg
	python mkPatternId.py 40 1 > pattern-id-40-1.svg
	python mkPatternId.py 40 2 > pattern-id-40-2.svg
	python mkPatternId.py 40 3 > pattern-id-40-3.svg
	python mkPatternId.py 40 4 > pattern-id-40-4.svg
	python mkPatternId.py 40 5 > pattern-id-40-5.svg
	python mkPatternId.py 40 6 > pattern-id-40-6.svg
	python mkPatternId.py 40 7 > pattern-id-40-7.svg

clean:
	rm -f *.svg
